### ISSUE TITLE
Connect call failed 

### ISSUE THREAD

**Issue by PrashantBaid11** [PythonistaGuild/Wavelink#115]
Here is the code.
```python
from discord.ext import commands
from youtube_dl import YoutubeDL
import discord
from utilities import help_embed
import wavelink

class Music(commands.Cog, wavelink.WavelinkMixin):
    def __init__(self, bot):
        self.client = bot
        self.wavelink = wavelink.Client(bot=bot)
        self.client.loop.create_task(self.start_nodes())

    @commands.Cog.listener()
    async def on_voice_state_update(self, member, before, after):
        if not member.bot and after.channel is None:
            if not [m for m in before.channel.members if not m.bot]:
                pass

    @wavelink.WavelinkMixin.listener()
    async def on_node_ready(self, node: wavelink.Node):
        print(f"{node.identifier} is ready")

    
    async def start_nodes(self):
        await self.client.wait_until_ready()

        await self.wavelink.initiate_node(host='127.0.0.1',
                                              port=2333,
                                              rest_uri='http://127.0.0.1:2333',
                                              password='youshallnotpass',
                                              identifier='MAIN',
                                              region=['us_central', 'europe', 'asia'])

    def get_player(self, ctx: commands.Context):
        return self.wavelink.get_player(ctx.guild.id)

    @commands.command(name='play', description="Plays a song", aliases=['p'])
    async def play(self, ctx, *song_name):
        song_name = ' '.join(song_name)
        tracks = self.wavelink.get_tracks(f'ytsearch: {song_name}')

        print(tracks[0])

def setup(bot):
    bot.add_cog(Music(bot))
```

Error:
```
WEBSOCKET | Connection Failure:: Cannot connect to host 127.0.0.1:2333 ssl:default [Connect call failed ('127.0.0.1', 2333)]
Traceback (most recent call last):
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 2333)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/wavelink/websocket.py", line 76, in _connect
    self._websocket = await self._node.session.ws_connect(uri, headers=self.headers, heartbeat=self._node.heartbeat)
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/prash/.local/share/virtualenvs/PrashBot-FEZGVm37/lib/python3.9/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:2333 ssl:default [Connect call failed ('127.0.0.1', 2333)]
```

**Comment by Motzumoto** [comment]
Make sure you're starting the jar file before you launch your bot
