### ISSUE TITLE
'_MissingSentinel' object has no attribute 'guild'

### ISSUE THREAD

**Issue by ArynRama** [PythonistaGuild/Wavelink#152]
Hi, can someone please help.
I created a discord bot but my terminal keeps getting spammed with this error (everthing works fine.):
```Task exception was never retrieved
future: <Task finished name='Task-128' coro=<Websocket.process_data() done, defined at C:\Users\aryan\Documents\Workspace\Bots\BBB-Discord-Bot\.venv2\lib\site-packages\wavelink\websocket.py:137> exception=AttributeError("'_MissingSentinel' object has no attribute 'guild'")>
Traceback (most recent call last):
  File "C:\Users\aryan\Documents\Workspace\Bots\BBB-Discord-Bot\.venv2\lib\site-packages\wavelink\websocket.py", line 147, in process_data
    player = self.node.get_player(self.node.bot.get_guild(
  File "C:\Users\aryan\Documents\Workspace\Bots\BBB-Discord-Bot\.venv2\lib\site-packages\wavelink\pool.py", line 309, in get_player
    if player.guild == guild:
  File "C:\Users\aryan\Documents\Workspace\Bots\BBB-Discord-Bot\.venv2\lib\site-packages\wavelink\player.py", line 107, in guild
    return self.channel.guild
AttributeError: '_MissingSentinel' object has no attribute 'guild'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D54502A050>```

**Comment by chillymosh** [comment]
@ArynRama which discord version are you on? Which fork are you using? 
I am going to assume you are using the latest version of wavelink but either the 1.7.3 version of dpy or a fork that has changed the namespace.
