### ISSUE TITLE
TypeError: 'coroutine' object is not callable

### ISSUE THREAD

**Issue by Kaz213** [PythonistaGuild/Wavelink#170]
I'm getting this error when I try and play music on using my discord bot.

Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Websocket.process_data() done, defined at C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\websocket.py:137> exception=TypeError("'coroutine' object is not callable")>
Traceback (most recent call last):
  File "C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\websocket.py", line 156, in process_data
    event, payload = await self._get_event_payload(data['type'], data)
  File "C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\websocket.py", line 184, in _get_event_payload
    track = await self.node.build_track(cls=wavelink.Track, identifier=base64_)
  File "C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\pool.py", line 294, in build_track
    return cls(identifier, data)
TypeError: 'coroutine' object is not callable
Task exception was never retrieved
future: <Task finished name='Task-39' coro=<Websocket.process_data() done, defined at C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\websocket.py:137> exception=TypeError("'coroutine' object is not callable")>
Traceback (most recent call last):
  File "C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\websocket.py", line 156, in process_data
    event, payload = await self._get_event_payload(data['type'], data)
  File "C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\websocket.py", line 184, in _get_event_payload
    track = await self.node.build_track(cls=wavelink.Track, identifier=base64_)
  File "C:\Users\icep2\AppData\Local\Programs\Python\Python39\lib\site-packages\wavelink\pool.py", line 294, in build_track
    return cls(identifier, data)
TypeError: 'coroutine' object is not callable

**Comment by EvieePy** [comment]
Can you please provide the full code you are using?
You can paste it here: https://mystb.in/

**Comment by EvieePy** [comment]
You need to paste it, click save and then send the link it creates

**Comment by Kaz213** [comment]
https://mystb.in/BeatlesPillJill.python

**Comment by Kaz213** [comment]
where can i find the docs for how the queue works?

**Comment by Kaz213** [comment]
Thank you also should I close the Issue or is that for you to do?

**Comment by EvieePy** [comment]
I will close this issue. If you need further assistance consider joining the official [discord server](https://discord.gg/RAKc3HF).

**Comment by Kaz213** [comment]
![image](https://user-images.githubusercontent.com/107991042/174997283-c284863d-c936-4eb3-8001-657e245e41cc.png)

**Comment by EvieePy** [comment]
What is your Discord name, have you been previously banned from the server?

**Comment by Kaz213** [comment]
Nevermind its because i was using a VPN
