### ISSUE TITLE
Lavalink succesfully loads the song, bot seems to use voice but player doesn't send song

### ISSUE THREAD

**Issue by OhhTuRnz** [PythonistaGuild/Wavelink#241]
Hello, while using the sample code you pass for checking if this would be a good solution to run my bot, i have this error.

```
Logs of lavalink are:
2023-09-14 13:22:43.175  INFO 32648 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=Z5NoQg8LdDk"
2023-09-14 13:22:43.179  WARN 32648 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
2023-09-14 13:22:43.427  INFO 32648 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id (current is null).
2023-09-14 13:22:43.498  INFO 32648 --- [ader-2-thread-1] c.s.d.l.s.y.YoutubeAccessTokenTracker    : Updating YouTube visitor id succeeded, new one is CgtGamZhQ2NJMmxGUSj924uoBjIGCgJFUxIAOgogkaXnpdC_u4Fl, next update will be after 600 seconds.
2023-09-14 13:22:43.575  INFO 32648 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Loaded track Polyphia - Playing God (Official Music Video)
2023-09-14 13:23:39.795  WARN 32648 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Query: SELECT NAME,PERCENTDPCTIME,PERCENTINTERRUPTTIME,PERCENTPRIVILEGEDTIME,PERCENTPROCESSORTIME,PERCENTUSERTIME FROM Win32_PerfRawData_Counters_ProcessorInformation WHERE NOT Name LIKE "
%_Total"
2023-09-14 13:23:39.801  WARN 32648 --- [pool-2-thread-1] o.util.platform.windows.WmiQueryHandler  : COM exception: Invalid Query: SELECT NAME,PRIORITY,CREATIONDATE,PROCESSID,PARENTPROCESSID,READTRANSFERCOUNT,WRITETRANSFERCOUNT,PRIVATEPAGECOUNT,PAGEFAULTSPERSEC FROM Win32_Process WHERE NOT Name LIKE"%_Total"
2023-09-14 13:23:39.824 ERROR 32648 --- [pool-2-thread-1] lavalink.server.io.StatsCollector        : Exception while sending stats

java.lang.NullPointerException: Cannot invoke "oshi.software.os.OSProcess.getKernelTime()" because "p" is null
        at lavalink.server.io.StatsCollector.getProcessRecentCpuUsage(StatsCollector.kt:58) ~[classes!/:na]
        at lavalink.server.io.StatsCollector.retrieveStats(StatsCollector.kt:106) ~[classes!/:na]
        at lavalink.server.io.StatsCollector.createTask$lambda$0(StatsCollector.kt:69) ~[classes!/:na]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

My lavalink installed is 3.7.8 and my wavelink installed is 2.6.5

**Comment by chillymosh** [comment]
Are you using/have installed a language pack that is not English?
I recall seeing Lavalink have issues processing and finding column names for processes when using other languages.

**Comment by OhhTuRnz** [comment]
Thing was my jdk path was not aiming the right position. I was using jdk-17 but from my local java paths and not the one modified with the lavalink.jar and application.yml, just changed my local JAVA_HOME var for my jdk-1.x.x.x path and worked perfectly.

Thanks for your fast response!
